### PR TITLE
merge Thomas changes to my fork

### PR DESCRIPTION
**Pull request by RikardGrass**

### CODE REVIEW

**Comment by RikardGrass** [comment]
all ok

**Comment by RikardGrass** [comment]
ok

**Review by thooh92 — APPROVED** [review]

**Review by RikardGrass — COMMENTED** [review]
all ok

**Review by thooh92 — APPROVED** [review]

**Review by RikardGrass — COMMENTED** [review]
review is now finished

**Comment by RikardGrass** [comment]
stoped this request

**Pull request closed without merging**
